### ISSUE TITLE
Broken example in documentation, `breakfast.jlso` not found.

### ISSUE THREAD

**Issue by racinmat** [invenia/JLSO.jl#100]
In https://invenia.github.io/JLSO.jl/v2.5/metadata/
the example is broken, because the jlso file in the beginning is not found. Without it, it's quite hard to see that is going on with metadata.

**Comment by rofinn** [comment]
Thanks, had to do some digging to figure out why that didn't break our builds, looks like a distinction between `@repl` and `@example`. #101 should address the immediate issue and hopefully avoid similar issues in the future. You can access the preview docs [here](https://invenia.github.io/JLSO.jl/previews/PR101/metadata/) prior to that PR being merged.
