### ISSUE TITLE
Stop serializing version numbers as VersionNumbers in the metadata

### ISSUE THREAD

**Issue by oxinabox** [invenia/JLSO.jl#12]
One of the goals is that the metadata at least should be always recoverable.
We can consider this in 2 senses.
1. It loads in all julia versions on all platforms
2. It can be easily read with a BSON editor or really a text editor (since it is basically JSON)

The use of `VersionNumbers` is problematic on both counts.
It has `Varargs` typed fields 
https://github.com/JuliaLang/julia/blob/v1.1.1/base/version.jl#L27-L28
These are not portable between 32bit and 64bit systems (point 1).
Further, since it is such a complicated type, it is really hard to inspect manually. (point 2).

I propose that we should instead serialize them as strings.
and then parse them when loading the file, for packages.

I also propose that for the Julia Version, we store `sprint(versioninfo)`
instead of just `VERSION`.
Because that will include information about the archetecture, which will be needed if this kinda thing occurs in the serialized objects.

This change I think can be done in a backwards compatible way. I.e. we should be able to still load things that store the metadata as `VersionNumber`s.
We might want to leave it for version 3.0 of the format.

Alternatively, (/in addition) we could also get BSON.jl to fix this. though I am yet to completely confirm it.)

**Comment by oxinabox** [comment]
I have tested BSON.jl on its own and it doesn't seem to have a problem with this.
I still think it would be good not to use such a complex julia type though for reason 2

**Comment by rofinn** [comment]
Closed as of #28. NOTE: This also reduced the size of the BSON/JLSO metadata
