### ISSUE TITLE
Remove AWS dependencies

### ISSUE THREAD

**Issue by iamed2** [invenia/JLSO.jl#2]
These don't have a conceptual connection to the JLSO format or usage and should be removed to a calling package (Checkpoints?). Also, AWSSDK has enormous amounts of code and is known to increase compile/load time. AWSCore or a dedicated service package (e.g., AWSTools or AWSS3 for S3) should be used instead.

**Comment by rofinn** [comment]
Yeah, the only dependency JLSO.jl should have is BSON.jl.

**Comment by fchorney** [comment]
ah yes I see. I shall open up another branch once I get the 0.6 removal one done.

**Comment by fchorney** [comment]
hmm, looks like it at least needs describe_jobs? https://github.com/invenia/JLSO.jl/blob/master/src/JLSO.jl#L263

**Comment by rofinn** [comment]
We should probably remove that logic and maybe have it just check if an image environment variable is set. We can always choose to set that in an entrypoint script if necessary.
