### ISSUE TITLE
metadata for packages should use UUIDs

### ISSUE THREAD

**Issue by KristofferC** [invenia/JLSO.jl#22]
Currently, packages are stored by name which is not how packages are identified in the rest of Julia (they are identified by UUID). 

In addition, it seems that only packages in the Project (but not those only in the Manifest) are stored which is not enough to reproduce the package state.

Also, the `Pkg.installed` command is going away in 1.4 (in favor of `Pkg.dependencies()`).

I don't really see why you are not just bundling the Project + Manifest if reproducibility of these files is the goal.

**Comment by oxinabox** [comment]
Yes, this is covered by #6 "Store Manifest.toml"

The fact that it doesn't, is because this was originally written for julia 0.5,
and that metadata feature just hasn't been updated yet.

**Comment by KristofferC** [comment]
Cool, missed that.
