### ISSUE TITLE
Add ability too activate enviroment defined in the JLSO

### ISSUE THREAD

**Issue by oxinabox** [invenia/JLSO.jl#29]
follow up to #28 

> need functions that will let us get into a state where we can activate or instantiate a project.toml or manifest.toml from a JLSO

> Please open a separate issue for that. This PR is already rather big. That's also likely to be a more challenging problem to handle reliably. For example, since different environments share the same loaded code we'd likely need to:

>1. Write the Project.toml and Manifest.toml file to a temporary directory
>2. Startup an entirely new julia repl in the temporary directory using those environment files

_Originally posted by @rofinn in https://github.com/invenia/JLSO.jl/pull/28#issuecomment-542922992_

---

I don't think we want to start a new julia session.
We either want to write to a folder and then call `Pkg.activate(path)`
or call `push!(Base.LOAD_PATH, path)` 
depending on if we want to deactivated the current envirioment or not.
then run `Pkg.resolve()`

We don't want to deal with the case that they already have a package loaded at a different version,
because that is really hard,
and any resolution we can do is confusing.
We might want to explain it and suggest that if you run into troubles that the first thing you do before loading packages it activate the enviroment of the JLSO.
And if you really run into troubles because the version of one of JLSO'd dependencies has changed, then export the enviroment files, exit julia and activate them before loading the JSLO.
But these cases should be manual.

**Comment by rofinn** [comment]
Okay, If we don't care about being able to load the package from that new environment then I think just adding a `Pkg.activate` dispatch should handle most of what we want:

`Pkg.activate(::JLSOFile, path)`: Will write the Project.toml and Manifest.toml files to the specified path and then call `Pkg.activate(path)` on that.

From there all other `Pkg` calls should work as expected (e.g., `Pkg.instantiate`, `Pkg.resolve`, `Pkg.add`)

**Comment by oxinabox** [comment]
yes.
