### ISSUE TITLE
Massive load time for Julia 1.3+

### ISSUE THREAD

**Issue by colinxs** [invenia/JLSO.jl#33]
First off, awesome package! I've really enjoyed it so far. Unfortunately I came across an issue with load time while trying out Julia 1.3.

In the following example:
```julia
f = tempname() * ".jlso"
JLSO.save(f, :x=>rand(1000), :y=>rand(1000)) 
x = JLSO.load(f)
```

The _first_ call to JLSO.load(f) takes 1-2 minutes with Julia 1.3 (rc2, rc3, and rc4.1) on multiple machines, but only a few seconds with Julia 1.2. This is true for any level of compression or serializer. The difference appears to only be from compile time, as subsequent loads for other files are fast.

**Comment by oxinabox** [comment]
Julia 1.3 has not been released yet, because of these kinds of issues.

**Comment by rofinn** [comment]
Looks like this might be fixed on 1.3-rc5 https://github.com/JuliaLang/julia/issues/33615

**Comment by colinxs** [comment]
Looks like RC5 fixed it! In a fresh session:
```julia
julia> f = tempname() * ".jlso";
julia> JLSO.save(f, :x=>rand(1000), :y=>rand(1000));
julia> @time JLSO.load(f);
  2.822424 seconds (16.27 M allocations: 781.691 MiB, 9.60% gc time)
```

**Comment by colinxs** [comment]
I forgot to add: the slowdown came from `_upgrade_env(pkgs::Dict)` in `deprecations.jl`, and unfortunately there's still a relatively high penalty from it. Without it:
```julia
julia> @time JLSO.load(f);
1.372000 seconds (4.57 M allocations: 234.462 MiB, 2.11% gc time)
```

**Comment by rofinn** [comment]
Is that also still a 1-time cost or is it twice as expensive every time you call `JLSO.load`?
