### ISSUE TITLE
Upgrading to JLSO v3 is tedious for many files with package name conflicts

### ISSUE THREAD

**Issue by rofinn** [invenia/JLSO.jl#34]
When working with multiple registries it can be tedious to upgrade many JLSO files to v3 which will prompt to select a registry for each file being upgraded. It might be good to give an upgrade option that either ignores trying to convert `pkgs` => `project`, `manifest` or support passing those fields if we already know them. Even a `batch_upgrade` option would help.

**Comment by oxinabox** [comment]
I think we need to change it so that upgrading doesn’t try and make a real manifest.
Because that is super involved.
the update path should probably just do something that doesn’t work to make a real instantiatable enviroment,
but that gives you the info you want, and errors gracefully

**Comment by rofinn** [comment]
I think that's a good way to have bad/broken JLSO files. I think the work around for this might address that to some extent. What I'm currently doing is something like this:

```
# Normally upgrade the first file. We're assuming all other files were created from the same environment.
base_jlso = read(string(jlso_files[1]), JLSOFile)

# Manual upgrading to avoid being prompted about pkg conflicts
for fp in jlso_files[2:end]
    raw_dict = BSON.load(string(fp))
    empty!(raw_dict["metadata"]["pkgs"])
    d = JLSO.upgrade_jlso(raw_dict)
    jlso = JLSOFile(
        VersionNumber(d["metadata"]["version"]),
        VersionNumber(d["metadata"]["julia"]),
        Symbol(d["metadata"]["format"]),
        Symbol(d["metadata"]["compression"]),
        d["metadata"]["image"],
        base_jlso.project,
        base_jlso.manifest,
        Dict{Symbol, Vector{UInt8}}(Symbol(k) => v for (k, v) in d["objects"]),
    )
    write(fp, jlso)
end
```

**Comment by oxinabox** [comment]
> I think that's a good way to have bad/broken JLSO files. I think the work around for this might address that to some extent. What I'm currently doing is something like this:

Only does upgrade write to disk?

I didn't know that.
the v1->v2 upgrade didn't.

Fair enough

**Comment by rofinn** [comment]
You're correct, upgrading doesn't currently write to disk by default, but we may want to support that in the batch updating API.

**Comment by oxinabox** [comment]
As you insist JLSO files are not for long term storage. 
I feel like upgrading then then writing them to disk is kinda a odd and not worth it pattern?

**Comment by rofinn** [comment]
Yeah, but we already knew that was an issue with switching to storing the Manifest. I think doing our best to help people upgrade file formats is better than nothing. It'd probably also be good to layer the API more to help people know how to debug a JLSO file when things don't work. Maybe an example of loading and interpreting the raw BSON would help?

**Comment by oxinabox** [comment]
> Yeah, but we already knew that was an issue with switching  to storing the Manifest. I think doing our best to help people upgrade  file formats is better than nothing. 

But it isn't something to spend too much time on, because the gains are not huge.


> . It'd probably also be good to layer the API more to help people know how to debug a JLSO file when things don't work. Maybe an example of loading and interpreting the raw BSON would help?

Yes. that would be great.
