### ISSUE TITLE
loading StaticArrays caused JLSO.load times to skyrocket?

### ISSUE THREAD

**Issue by colinxs** [invenia/JLSO.jl#42]
With JLSO@v1.3.0 and StaticArrays@v0.12.1 I'm seeing the following:

```
julia> using JLSO
julia> open("/tmp/foo.jlso", "w") do io
            write(io, JLSOFile(:data => rand(1000)))
          end
julia> @time JLSO.load("/tmp/foo.jlso")
  5.034648 seconds (16.27 M allocations: 781.737 MiB, 7.60% gc time)
```
vs
```
julia> using StaticArrays, JLSO
julia> open("/tmp/foo.jlso", "w") do io
            write(io, JLSOFile(:data => rand(1000)))
          end
julia> @time JLSO.load("/tmp/foo.jlso")
  172.650491 seconds (259.65 M allocations: 16.296 GiB, 4.05% gc time)
```

Second call to JLSO.load is still fast, however. Here's my `versioninfo()` but I'm seeing this across multiple machines.
```
Julia Version 1.3.1
Commit 2d5741174c (2019-12-30 21:36 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2697 v2 @ 2.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, ivybridge)
```

Let me know if this issue should be moved to StaticArrays and I'll move it over.

**Comment by colinxs** [comment]
Interestingly, calling `JLSO.load(io)` loads quickly:
```julia
julia> @time open(io -> JLSO.load(io), "/tmp/foo.jlso")
 11.904374 seconds (42.70 M allocations: 2.202 GiB, 6.61% gc time)
```
```julia
julia> @time JLSO.load("/tmp/foo.jlso")
171.802980 seconds (252.72 M allocations: 15.957 GiB, 4.68% gc time)
```

**Comment by colinxs** [comment]
So removing the line `d = JLSO.upgrade_jlso(parsed)` in `JLSO.load` appears to "fix" this issue:
```julia
julia> @time myload("/tmp/foo.jlso")
  1.877981 seconds (3.18 M allocations: 160.519 MiB, 2.29% gc time)
```
and is not affected by StaticArrays being loaded.

So it seems like this is related to #33 and that not all the issues were fleshed out.

**Comment by oxinabox** [comment]
This probably needs to be taken up on JuliaLang/julia.

I don't think it's on us.

**Comment by colinxs** [comment]
Yeah that appears to be the case (a lot of time appears to be spent in `jl_intersect_types`), but there may be a few workarounds that can be done here.

I added a PR (#43) that changes the signature of `_upgrade_jlso` which appears to cut down the first `load` time from 170s to about 20s.

As additional step, would the devs here consider removing the call to `upgrade_jlso` in `Base.read` and instead just failing with a kind message to call `upgrade(src, dst)` directly (possibly exposing an in-memory equivalent to `upgrade(src, dst)`? This would also align with Julia's serialization which doesn't promise backwards compatibility.

I've been building some features around JLSO for a soon-to-be-released [robotics/control/RL framework](https://github.com/Lyceum) and the JLSO load times have been a common complaint among beta testers. The 1.8s load time is awfully attractive and would definitely be appreciated.

But that's just my 0.02 cents :)

**Comment by oxinabox** [comment]
I have verified that this is happening and that #43 mostly fixes it.
this is still really problematic and weird and an unstream issue in JuliaLang/julia needs to be openned.

**Comment by oxinabox** [comment]
https://github.com/JuliaLang/julia/issues/34681

**Comment by colinxs** [comment]
Thanks for filing that issue on JuliaLang/julia; I'm interested to know what's actually causing this.
