### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by haampie** [invenia/JLSO.jl#48]
I'm writing a list of datasets to disk and I found JLSO.jl to be convenients because I can ship things as a single, compressed file and load only parts of it. The uncompressed data is ~12GB.

However, I'm a bit confused about how JLSO works: it seems to be incredibly slow when I call `.save(...)`, and for minutes not a single byte is written to disk.

After a while the process might get killed because it runs out of memory.

So my question is: is JLSO copying input data at any point? And shouldn't it write to disk from the start?

**Comment by oxinabox** [comment]
When `save` is called:
 1. The JLSO file is created in memory. This includes storing in memory a compressed copy of everything.
 2. The JLSO file is written to disk, this involves wrapping the whole thing in a out BSON layer containing metadata, with the inner data field being the all the items that are stores (which are binary blobs at this point. Either compressed BSON or compressed julia serializer)

In theory one could interleave the compression and writing.

I believe when JLSO was originally designed the intent was that the `JLSOFile` would be assembled-by-hand element at a time, during the exectuion of a longer program.
Then at the end it would be written to disk with `write`

`save` was (I believe) a late addition to the API.

Though it is now my belief that all current uses of JLSO always write the object immediately after.
(I know there used to be a thing that didn't but that is no longer used.)

**Comment by haampie** [comment]
> In theory one could interleave the compression and writing.

That would be great! Another thing that comes to mind is being able to append to a jlso on disk without loading it entirely (not sure if possible). Or I should just buy more RAM or split things up in multiple jlso files.

W.r.t. performance: saving ~10GB of data which compresses to 750MB takes `363.826390 seconds (6.33 M allocations: 11.908 GiB, 0.58% gc time)`. Maybe there's a type instability or something? I'll check it when I have time

**Comment by oxinabox** [comment]
> being able to append to a jlso on disk without loading it entirely (not sure if possible).

Not trivial as the outer file format is BSON. And BSON requires closing brackets.
But not impossible

> Otherwise, everything seems to be single threaded, and since the package targets larger data sets (from the readme), maybe it's not a bad idea to sprinkle `@spawn`?

Yeah, and that could be done without rearchitecting the whole thing.
Assuming the serializer and compression is itself thread safe

**Comment by haampie** [comment]
Closing this since #51 is merged now :)
