### ISSUE TITLE
Store Manifest.toml in file metadata

### ISSUE THREAD

**Issue by nickrobinson251** [invenia/JLSO.jl#6]
This would give greater reproducibility than saving `Pkg.installed()::Dict` but it's probably a lot more data. 

Currently `Base.active_project()` gives the path to the Project.toml, so to get the Manifest: `joinpath(dirname(Base.active_project()), "Manifest.toml")`.

Also it's not _perfect_ reprodicibility, since environments stack, for that I think we'd need all the Manifest.toml files in `Base.load_path()` but relying on the full stack probably only happens when running scripts, and then there's no nice way to `Pkg.instantiate()` a stack of environments anyway.

**Comment by oxinabox** [comment]
I think we will need to do this for julia-1.4
as I think `Pkg.installed` is going away.

Also want to prioritize it anyway as `Pkg.installed` is fairly misleading, at best.
Compared to even the top-level Manifest.toml
