### ISSUE TITLE
Introduce compressed format: .JLSO.gz

### ISSUE THREAD

**Issue by oxinabox** [invenia/JLSO.jl#7]
I just did a quick test and we can compress a Fairly typical JLSO file containing a DataFrame
from  `611KB` down to `67KB`.

BSON.jl can already handle working with IO streams
and
CodecZlib.jl can already do GZip IO streams 

So this feels fairly easy and I think the gains a pretty good.

**Comment by iamed2** [comment]
We should allow for multiple compressed formats; maybe any streamable compression from the Codec* packages?

**Comment by iamed2** [comment]
Gzip is probably the best start though
