### ISSUE TITLE
Citation?

### ISSUE THREAD

**Issue by biona001** [invenia/JLSO.jl#70]
I'm using JLSO.jl for one of my research papers and I wish to cite this package. Is there a bibtex file or should I just make one myself?

**Comment by oxinabox** [comment]
you should make one youself.

Though @rofinn what do you think of submitting JLSO to JOSS?

**Comment by rofinn** [comment]
Okay, I had a quick look at JOSS and I don't think this package really fits. It isn't a very research focused tool even if we often use it for research datasets. I don't think JLD2.jl, CSV.jl or BSON.jl would really make sense either. That being said, we could choose to add DOIs to our repos on GitHub regardless?

https://guides.github.com/activities/citable-code/

**Comment by biona001** [comment]
You can get a DOI from [Zenodo](https://zenodo.org/), but ok I'll make a bibtex myself, and update it if there's something else I should use.

**Comment by oxinabox** [comment]
At least two similar packages for python have a JOSS paper: https://joss.theoj.org/papers/10.21105/joss.01115, https://joss.theoj.org/papers/10.21105/joss.00766

and in R land they will write a JOSS paper about anything: https://joss.theoj.org/papers/10.21105/joss.00185, https://joss.theoj.org/papers/10.21105/joss.00910,

**Comment by rofinn** [comment]
Alright, I'm down to give it a shot if you want.

**Comment by oxinabox** [comment]
Lets register for a Zenodo url now since will need one to post to JOSS anyway

**Comment by oxinabox** [comment]
Things a paper should cover:

 - Fundermentally 2 types of serialization (but no doubt exceptions exist)
    - Restricted types, Cross-language, Secure, robust to underling resentation code changes. like JSON, pure BSON, pure HDF5, CSV
    - Unrestricted types, Single-language, (generally) vulnerable to abitary code injection, not-robust to code changes. Like Julia Serializers, Python's Pickle, BSON.jl's julia specific extensions,  JLD/JLD2 HDF5 extensions, MatLab's .mat HDF5 extension

One wants to use the later category as it is generally convient to be able to work with the types that are convient. 
Though for long term archieve and sharing one needs to swap to the first category;
people often don't realise what is important to save til long after and might only have these short term serialized objects about.
Making sure those can actually be openned when source code has changed is crucial for being able to access old work.

JLSO: container for these unresticted serialisers, that adds enough metadata that they can be sure to be able to be openned again.
Also adds compression.
