### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by oxinabox** [invenia/JLSO.jl#85]
Is there a reason a release hasn't been tagged?
Normally, I would go ahead and tag one,
but now i am surpsicious, since there has been so many commits since the last release.

In particular  the oversized BSON thing is fixed

**Comment by rofinn** [comment]
I was looking into address #68 and #76, but I guess that can wait till another release as neither would be breaking.

**Comment by oxinabox** [comment]
Yes, this would be a minor release
